pipeline {
    agent any
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from Git') {
            steps {
                git branch: 'main', url: 'https://github.com/Shaik-DevOpsLucky/devsecops-Tetris-V1.git'
            }
        }

        stage('Terraform Version') {
            steps {
                sh 'terraform --version'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('EKS_TERRAFORM') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform plan') {
            steps {
                dir('EKS_TERRAFORM') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform validate again') {
            steps {
                dir('EKS_TERRAFORM') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('EKS_TERRAFORM') {
                    sh 'terraform ${action} --auto-approve'
                }
            }
        }
    }
}


## Configure choice perameters "action" -->> apply and destroy
